inventory/locations/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from inventory.models import Location

class LocationForm(FlaskForm):
    location_name = StringField('Location Name', validators=[DataRequired()])
    submit = SubmitField('Add Location')

    def validate_location_name(self, location_name):
        location = Location.query.filter_by(location_name=location_name.data).first()
        if location:
            raise ValidationError('That location is available. Please choose a different one.')

inventory/product_movements/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired

class ProductMovementForm(FlaskForm):
    from_location = SelectField(u'From', coerce=int)
    to_location = SelectField(u'To', coerce=int)
    product_id = SelectField('Product Name', coerce=int, validators=[DataRequired()])
    qty = IntegerField('Quantity', validators=[DataRequired()])
    submit = SubmitField('Move Product')

inventory/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from inventory.models import Product

class ProductForm(FlaskForm):
    product_name = StringField('Product Name', validators=[DataRequired()])
    submit = SubmitField('Add Product')

    def validate_product_name(self, product_name):
        product = Product.query.filter_by(product_name=product_name.data).first()
        if product:
            raise ValidationError('That product is available. Please choose a different one.')

inventory/locations/__init__.py
#Comment

inventory/locations/routes.py
from flask import (render_template, url_for, flash, redirect, request, Blueprint)
from inventory import db
from inventory.models import Location
from inventory.locations.forms import LocationForm

locations = Blueprint('locations', __name__)

@locations.route("/location/new", methods=['GET', 'POST'])
def new_location():
    form = LocationForm()
    if form.validate_on_submit():
        location = Location(location_name=form.location_name.data)
        db.session.add(location)
        db.session.commit()
        flash('Your location is successfully added in the location list!', 'success')
        return redirect(url_for('main.location'))
    return render_template('create.html', form=form, legend='New Location')


@locations.route("/location/<int:location_id>/update", methods=['GET', 'POST'])
def update_location(location_id):
    location = Location.query.get_or_404(location_id)
    form = LocationForm()
    if form.validate_on_submit():
        location.location_name = form.location_name.data
        db.session.commit()
        flash('Your location has been updated!', 'success')
        return redirect(url_for('main.location', location_id=location.location_id))
    elif request.method == 'GET':
        form.location_name.data = location.location_name
    form.submit.label.text = 'Update Location'
    return render_template('create.html', title='Update Location', form=form, legend='Update Location') 

@locations.route("/location/<int:location_id>")
def location(location_id):
    location = Location.query.get_or_404(location_id)
    return render_template('location.html', title='Update Location', location=location)


@locations.route("/location/<int:location_id>/delete", methods=['POST'])
def delete_location(location_id):
    location = Location.query.get_or_404(location_id)
    db.session.delete(location)
    db.session.commit()
    flash('Your location has been deleted!', 'success')
    return redirect(url_for('main.location'))

inventory/main/routes.py
from flask import render_template, request, Blueprint
from inventory.models import Product, Location, ProductMovement
from inventory import db

main = Blueprint('main', __name__)

#inventory
@main.route("/")
@main.route("/product")
def product():
    products = Product.query.order_by(Product.product_name).all()
    return render_template('product.html', title='Product',products=products)

@main.route("/location")
def location():
    locations = Location.query.order_by(Location.location_name).all()
    return render_template('location.html', title='Location',locations=locations)

@main.route("/product_movement")
def product_movement():
    product_movements = ProductMovement.query.order_by(ProductMovement.timestamp.desc()).all()
    products = Product.query
    return render_template('product_movement.html', title='Moved Product',product_movements=product_movements, products=products)


@main.route("/report")
def report():
    product_movements = db.session.query(ProductMovement.to_location, ProductMovement.product_id).filter(ProductMovement.from_location=="").distinct(ProductMovement.to_location).all()
    product = Product.query
    qty = ProductMovement.query
    return render_template('report.html', title='Report', product_movements=product_movements, qty=qty, product=product)

@main.route("/dashboard")
def dashboard():
    return render_template('dashboard.html', title='Dashboard')

inventory/product_movements/__init__.py
#Comment

inventory/product_movements/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from datetime import datetime
from inventory import db
from inventory.models import Product, Location, ProductMovement
from inventory.product_movements.forms import ProductMovementForm
from inventory.product_movements.utils import get_choices, convert_location_id_to_name, convert_location_name_to_id, product_movement_exist, error_conditions

product_movements = Blueprint('product_movements', __name__)

@product_movements.route("/product_movement/new", methods=['GET', 'POST'])
def new_product_movement():
    form = ProductMovementForm()

    get_choices(form)

    from_location = convert_location_id_to_name(form.from_location.data)
    to_location = convert_location_id_to_name(form.to_location.data)
    
    existing_product_movement = product_movement_exist(form, from_location, to_location)
    existing_only_from_location = product_movement_exist(form, "", from_location)
    existing_only_to_location = product_movement_exist(form, "", to_location)
    
    if form.validate_on_submit():
        error = error_conditions(form, from_location, to_location, existing_only_from_location, existing_only_to_location, 'new', '')
        if(error != 'No error'):
            return redirect(url_for('product_movements.new_product_movement'))
        else:
            #qty++ in to_location
            if existing_product_movement and \
               existing_product_movement.from_location == "" and \
               existing_product_movement.to_location != "":
                existing_only_to_location.qty = existing_only_to_location.qty + form.qty.data

            #qty-- in from_location
            elif existing_product_movement and \
                 existing_product_movement.from_location != "" and \
                 existing_product_movement.to_location == "":
                existing_only_from_location.qty = existing_only_from_location.qty - form.qty.data

            #qty++ in to_location and qty-- in from_location
            elif (existing_product_movement and \
                  existing_product_movement.from_location != "" and \
                  existing_product_movement.to_location != "" ) \
                  or (existing_only_to_location and existing_only_from_location):
                existing_only_to_location.qty = existing_only_to_location.qty + form.qty.data
                existing_only_from_location.qty = existing_only_from_location.qty - form.qty.data

            #decrement from from_location and then create to location
            elif existing_only_from_location and not existing_only_to_location:
                existing_only_from_location.qty = existing_only_from_location.qty - form.qty.data
                if to_location != "":
                    product_to = ProductMovement(from_location="", to_location=to_location, product_id=form.product_id.data, qty=form.qty.data)
                    db.session.add(product_to)
                    db.session.commit()

            #Do Nothing
            else:
                pass

            product_movement = ProductMovement(from_location=from_location, to_location=to_location, product_id=form.product_id.data, qty=form.qty.data)
            db.session.add(product_movement)
            db.session.commit()
            flash('Your product movement is successfully added in the product movement list!', 'success')
            return redirect(url_for('main.product_movement'))
    return render_template('create.html', form=form, legend='New Product Movement')


@product_movements.route("/product_movement/<int:movement_id>/update", methods=['GET', 'POST'])
def update_product_movement(movement_id):
    product_movement = ProductMovement.query.get_or_404(movement_id)
    form = ProductMovementForm()
    
    get_choices(form)

    from_location = convert_location_id_to_name(form.from_location.data)
    to_location = convert_location_id_to_name(form.to_location.data)

    existing_product_movement = product_movement_exist(form, from_location, to_location)
    existing_only_from_location = product_movement_exist(form, "", from_location)
    existing_only_to_location = product_movement_exist(form, "", to_location)

    if form.validate_on_submit(): 
        error = error_conditions(form, from_location, to_location, existing_only_from_location, existing_only_to_location, "update", product_movement.qty)
        if(error == 'No error'):
            #qty++ in to_location
            if existing_product_movement and existing_product_movement.from_location == "" and existing_product_movement.to_location != "":
                existing_only_to_location.qty = existing_only_to_location.qty + form.qty.data - product_movement.qty

            #qty-- in from_location
            elif existing_product_movement and existing_product_movement.from_location != "" and existing_product_movement.to_location == "":
                existing_only_from_location.qty = existing_only_from_location.qty - form.qty.data + product_movement.qty

            #qty++ in to_location and qty-- in from_location
            elif (existing_product_movement and existing_product_movement.from_location != "" and existing_product_movement.to_location != "") or (existing_only_to_location and existing_only_from_location):
                existing_only_to_location.qty = existing_only_to_location.qty + form.qty.data - product_movement.qty
                existing_only_from_location.qty = existing_only_from_location.qty - form.qty.data + product_movement.qty

            #decrement from from_location and then create to location
            elif existing_only_from_location and not existing_only_to_location:
                existing_only_from_location.qty = existing_only_from_location.qty - form.qty.data + product_movement.qty
                if to_location != "":
                    product_to = ProductMovement(from_location="", to_location=to_location, product_id=form.product_id.data, qty=form.qty.data)
                    db.session.add(product_to)
                    db.session.commit()

            #Do Nothing
            else:
                pass
            
            product_movement.from_location = from_location
            product_movement.to_location = to_location
            product_movement.product_id = form.product_id.data
            product_movement.qty = form.qty.data
            product_movement.timestamp = datetime.now()
            db.session.commit()
            flash('Your product movement has been updated!', 'success')
            return redirect(url_for('main.product_movement', movement_id=product_movement.movement_id))
    elif request.method == 'GET':

        form.from_location.data = convert_location_name_to_id(product_movement.from_location)
        form.to_location.data = convert_location_name_to_id(product_movement.to_location)
        form.product_id.data = product_movement.product_id
        form.qty.data = product_movement.qty
    form.submit.label.text = 'Update Product Movement'
    return render_template('create.html', title='Update Moved Product', form=form, legend='Update Moved Product') 

@product_movements.route("/product_movement/<int:movement_id>")
def product_movement(movement_id):
    product_movement = ProductMovement.query.get_or_404(movement_id)
    products = Product.query
    return render_template('product_movement.html', title='Update Moved Product', product_movement=product_movement, products=products)


@product_movements.route("/product_movement/<int:movement_id>/delete", methods=['POST'])
def delete_product_movement(movement_id):
    product_movement = ProductMovement.query.get_or_404(movement_id)
    db.session.delete(product_movement)
    db.session.commit()
    flash('Your product movement has been deleted!', 'success')
    return redirect(url_for('main.product_movement'))

inventory/products/__init__.py
#Comment

inventory/products/routes.py
from flask import (render_template, url_for, flash, redirect, request, Blueprint)
from inventory import db
from inventory.models import Product
from inventory.products.forms import ProductForm

products = Blueprint('products', __name__)

@products.route("/product/new", methods=['GET', 'POST'])
def new_product():
    form = ProductForm()
    if form.validate_on_submit():
        product = Product(product_name=form.product_name.data)
        db.session.add(product)
        db.session.commit()
        flash('Your product is successfully added in the product list!', 'success')
        return redirect(url_for('main.product'))
    return render_template('create.html', form=form, legend='New Product')


@products.route("/product/<int:product_id>/update", methods=['GET', 'POST'])
def update_product(product_id):
    product = Product.query.get_or_404(product_id)
    form = ProductForm()
    if form.validate_on_submit():
        product.product_name = form.product_name.data
        db.session.commit()
        flash('Your product has been updated!', 'success')
        return redirect(url_for('main.product', product_id=product.product_id))
    elif request.method == 'GET':
        form.product_name.data = product.product_name
    form.submit.label.text = 'Update Product'
    return render_template('create.html', title='Update Product', form=form, legend='Update Product') 

@products.route("/product/<int:product_id>")
def product(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('product.html', title='Update Product', product=product)


@products.route("/product/<int:product_id>/delete", methods=['POST'])
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)
    db.session.delete(product)
    db.session.commit()
    flash('Your product has been deleted!', 'success')
    return redirect(url_for('main.product'))

inventory/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}
    <div class="container px-5 py-3">
        <h2 class="mb-4">Dashboard</h2>
        
    </div>
{% endblock content %}

inventory/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    
    <!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" > -->
    <!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	
	<script src="https://kit.fontawesome.com/62e099589c.js" crossorigin="anonymous"></script>

    {% if title %}
        <title>Inventory App - {{ title }}</title>
    {% else %}
        <title>Inventory App</title>
	{% endif %}
	
</head>

<body>

	<div class="wrapper d-flex align-items-stretch">
		<nav id="sidebar">
			<div class="custom-menu">
				<button type="button" id="sidebarCollapse" class="btn btn-primary ">
					<i class="fa fa-bars"></i>
				</button>
			</div>
			<div class="p-4">
				<h1><a href="/" class="logo">Bike Shop Inventory</a></h1>
				<ul class="list-unstyled components mb-5">
					<!-- <li>
						<a href="/"><i class="fas fa-chart-pie mr-3"></i> Dashboard</a>
					</li> -->
					<li>
                        <a class="nav-item nav-link" href="{{ url_for('main.product') }}"><i class="fas fa-boxes mr-3"></i> Products</a>
					</li>
					<li>
						<a class="nav-item nav-link" href="{{ url_for('main.location') }}"><i class="fas fa-map-marker-alt mr-4"></i> Locations</a>
					</li>
					<li>
						<a class="nav-item nav-link" href="{{ url_for('main.product_movement') }}"><i class="fas fa-dolly mr-3"></i> Move Products</a>
					</li>
					<li>
						<a class="nav-item nav-link" href="{{ url_for('main.report') }}"><i class="fas fa-table mr-3"></i> Reports</a>
					</li>
				</ul>
			</div>
			
		</nav>
		<div id="content">
			<!-- Page Content  -->
			<div  class="p-4 px-md-4">
				{% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
						{% for category, message in messages %}
							<div class="alert alert-{{ category }} mx-5 ">
								{{ message }}
							</div>
						{% endfor %}
					{% endif %}
				{% endwith %}
				{% block content %}{% endblock %}
			</div>
		</div>
		
	</div>

    

	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- Other JavaScript -->
	<script src="{{ url_for('static', filename='main.js') }}"></script>

</body>

</html>

inventory/templates/location.html
{% extends "layout.html" %}
{% block content %}
    {% if title=='Location' %}
        <div class="container px-5 py-3">    
            <h2 class="mb-4 phead">{{ title }}s</h2>  
            <div class="row">
                <div class="ml-3">
                    <table class="table table-hover table-responsive table-bordered">
                        <tbody>
                            {% if not locations%}
                                <tr>
                                    <td colspan="3">No locations added. Please add location to view.</td>
                                </tr>
                            {% else %}
                                {% for location in locations %}
                                    <tr class="l">
                                        <!-- <td>{{ loop.index }}.</td> -->
                                        <td class="pl-3 first">{{ location.location_name }}</td>
                                        <td>
                                            <button type="button" class="btn btn-sm bt" data-toggle="modal" data-target="#deleteModal{{ location.location_id }}">
                                                <i class="fas fa-trash-alt pl-2"></i>
                                            </button>
                                            <a class="n" href="{{ url_for('locations.update_location', location_id=location.location_id) }}">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <div class="modal fade" id="deleteModal{{ location.location_id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <form action="{{ url_for('locations.delete_location', location_id=location.location_id) }}" method="POST">
                                                        <input class="btn btn-danger" type="submit" value="Delete">
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="add">
                    <button type="sbutton" id="sidebarCollapse" class="add-button btn btn-primary">
                        <a href="{{ url_for('locations.new_location') }}"><i class="fas fa-plus"></i></a>
                    </button><a class="add-text" href="{{ url_for('locations.new_location') }}"><i>Add Location</i></a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

inventory/templates/product.html
{% extends "layout.html" %}
{% block content %}
    {% if title=='Product' %}
        <div class="container px-5 py-3">  
            <h2 class="mb-4 phead">{{ title }}s</h2>  
            <!-- <div>
                <input class="search" id="myInput" type="text" placeholder="Search..">
            </div> -->
            <div class="row">
                <div class="ml-3">
                    <table class="table table-hover table-responsive table-bordered">
                        <tbody id="myTable">
                            {% if not products%}
                                <tr>
                                    <td colspan="3">No items found!! Please add product in the inventory.</td>
                                </tr>
                            {% else %}
                                {% for product in products %}
                                    <tr class="l">
                                        <!-- <td>{{ loop.index }}.</td> -->
                                        <td class="pl-3 first">{{ product.product_name }}</td>
                                        <td>
                                            <button type="button" class="btn btn-sm bt" data-toggle="modal" data-target="#deleteModal{{ product.product_id }}">
                                                <i class="fas fa-trash-alt pl-2"></i>
                                            </button>
                                            <a class="n" href="{{ url_for('products.update_product', product_id=product.product_id) }}">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <div class="modal fade" id="deleteModal{{ product.product_id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <form action="{{ url_for('products.delete_product', product_id=product.product_id) }}" method="POST">
                                                        <input class="btn btn-danger" type="submit" value="Delete">
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="add">
                    <button type="button" id="sidebarCollapse" class="add-button btn btn-primary">
                        <a href="{{ url_for('products.new_product') }}"><i class="fas fa-plus"></i></a>
                    </button><a class="add-text" href="{{ url_for('products.new_product') }}"><i>Add Product</i></a>
                </div>
            </div>
        </div>
    {% endif %}  
{% endblock content %}

inventory/templates/product_movement.html
{% extends "layout.html" %}
{% block content %}
    {% if title=='Moved Product' %}
        <div class="container px-5 py-3">  
            <div>
                <h2 class="mb-4 phead">{{ title }}s</h2> 
            </div>
            <div class="row">
                <div class="ml-3">
                    <table class="table table-hover table-responsive table-bordered">
                        <thead class="thead-light">
                            <tr>
                                <th>Product</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Quantity</th>
                                <th>Time Stamp</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if not product_movements%}
                                <tr>
                                    <td colspan="5">Add product to warehouse to see the movements.</td>
                                </tr>
                            {% else %}
                                {% for product_movement in product_movements %}
                                    <tr class="l">
                                        <td>{{ products.get(product_movement.product_id).product_name }}</td>
                                        <td>{{ product_movement.from_location }}</td>
                                        <td>{{ product_movement.to_location }}</td>
                                        <td>{{ product_movement.qty }}</td>
                                        <td>{{ product_movement.timestamp.strftime('%d/%m/%Y - %H:%M %p') }}</td>
                                        <td class="td">
                                            <button type="button" class="btn btn-sm bt" data-toggle="modal" data-target="#deleteModal{{ product_movement.movement_id }}">
                                                <i class="fas fa-trash-alt pl-2"></i>
                                            </button>
                                            <a class="n" href="{{ url_for('product_movements.update_product_movement', movement_id=product_movement.movement_id) }}">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <div class="modal fade" id="deleteModal{{ product_movement.movement_id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <form action="{{ url_for('product_movements.delete_product_movement', movement_id=product_movement.movement_id) }}" method="POST">
                                                        <input class="btn btn-danger" type="submit" value="Delete">
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="add">
                    <button type="button" id="sidebarCollapse" class="add-button btn btn-primary">
                        <a href="{{ url_for('product_movements.new_product_movement') }}"><i class="fas fa-plus"></i></a>
                    </button><a class="add-text" href="{{ url_for('product_movements.new_product_movement') }}"><i>Move Product</i></a>
                </div> 
            </div>
        </div>
    {% endif %}
{% endblock content %}